---
global:
  owner: kirankuc@amazon.com
  qsname: quickstart-codepipeline-bluegreen-deployment
  regions:
    - us-east-2
    - us-east-1
    - us-west-1
    - us-west-2
    #- ap-south-1
    #- eu-west-3
    - eu-west-2
    - eu-west-1
    #- ap-northeast-3
    - ap-northeast-2
    - ap-northeast-1
    #- sa-east-1
    - ca-central-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
  reporting: true
tests:
  taskcat:
    parameter_input: input.json
    template_file: quickstart-codepipeline-bluegreen-deployment.template
